semi: true
tabWidth: 2
printWidth: 120
singleQuote: true
trailingComma: all
arrowParens: always
overrides:
  - files:
      - "**/*.yml"
      - "**/*.yaml"
    options:
      singleQuote: false
      